### ISSUE TITLE
Error in IFC4x3_RC4.exp in definition of IfcSurfaceFeature

### ISSUE THREAD

**Issue by RickBrice** [bSI-InfraRoom/IFC-Documentation#6]
There seems to be a bust in IFC4x3_RC4.exp that was introduced in the last commit (0912a44). Should [RelatedSurfaceFeature](url) be `RelatedSurfaceFeature**s**`?

Commit e373044

![IfcSurfaceFeature_Commit_e373004](https://user-images.githubusercontent.com/37087370/126398410-c39b27d6-1207-4b9d-95a4-3d33cdf54992.PNG)

Commit 0912a44
![IfcSurfaceFeature_Commit_0912a44](https://user-images.githubusercontent.com/37087370/126398413-2b6d9f7e-974c-4f6a-b0c4-4cd9cf60104e.png)

I found this issue generating code for IfcOpenShell IfcParse library using the latest IFC4x3_RC4.exp file from this repository.

**Comment by RickBrice** [comment]
This issue seems to persist after the 9ffbab2 commit

**Comment by SergejMuhic** [comment]
Addressed here https://github.com/bSI-InfraRoom/IFC-Specification/pull/192.

**Comment by RickBrice** [comment]
The documentation seems to be updated. However the typo remains in https://github.com/bSI-InfraRoom/IFC-Documentation/blob/main/4_3_0_0/rc4/EXPRESS/IFC4x3_RC4.exp

**Comment by SergejMuhic** [comment]
There was no new release of the documentation (happens in this repository). Currently, we are gathering feedback before a new release. Could probably arrange it as there are no formal requirements currently.

The updated documentation, schema and properties are however on the IFC-Specification repository in the Actions tab as the workflows run on changes.

https://github.com/bSI-InfraRoom/IFC-Specification/actions 

You can filter the workflows on the left pane. Currently, I have three available:
- `schema-generation` (uploaded artifact is the generated EXPRESS schema)
- `property-quantity-listings-generation` (uploaded artifacts are the SPF and IFCXML of properties and quantities)
- `documentation-generation` (the whole HTML, EXPRESS, and XSD package that is also formally released in this repository)

I would therefore point you to the latest `documentation-generation` workflow for the corrected documentation.

https://github.com/bSI-InfraRoom/IFC-Specification/actions/runs/1144296658

I hope you do not see the process as too complex as with formal releases we need some formal approvals. Please feel free to give us feedback on the process as well. This would be much appreciated.

**Comment by RickBrice** [comment]
Thanks for the clarification. The confusion was my lack of understanding of the workflow.
